-
  name: Print Date
  hosts: localhost
  tasks:
    - name: Execute Date Command
      command: date
      register: current_date
    - name: Print Date
      debug:
        msg: "Date is {{ current_date.stdout }}"

-
  name: Echo
  hosts: localhost
  tasks:
    - name: Execute Echo
      command: echo 'Shariq'
